onlyBuiltDependencies:
  - '@hyperjump/json-pointer'
  - '@hyperjump/json-schema'
  - '@hyperjump/json-schema-core'
  - '@hyperjump/pact'
  - '@parcel/watcher'
  - '@swc/core'
  - lmdb
  - msgpackr-extract
  - protobufjs
  - unrs-resolver
